# exports next.js project to static site, and deploys exported files to S3
name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    environment: 
      name: demo
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - name: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: firebase-config.json
        json: '{"apiKey":"${{ secrets.FB_API_KEY }}", "authDomain":"${{ secrets.FB_AUTH_DOMAIN }}", "databaseURL":"${{ secrets.FB_DB_URL }}", "projectId":"${{ secrets.FB_PROJECT_ID }}", "storageBucket":"${{ secrets.FB_STORAGE_BUCKET }}", "messagingSenderId":"${{ secrets.FB_MSG_SENDER }}","appId":"${{ secrets.FB_APP_ID }}","measurementId":"${{ secrets.FB_MEASUREMENT_ID}}"}'
    - run: npm run build --if-present
    - name: deploy
      uses: reggionick/s3-deploy@v3
      with:
          folder: out
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: eu-west-2
